apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::712555685322:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::712555685322:role/eksctl-eksctl-demo-nodegroup-ng-7-NodeInstanceRole-1QMHIVNOKC1YM
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T01:19:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1603"
  uid: 058df234-b074-4f10-b10a-004ee9a1d400
